travis:
  secure:
    BINSTAR_TOKEN: K+JP4iUtIaa800uAbduq+mSMB5raY9J9yfmcvZO4MukTd+AcJSLt0Vi2WW7i+7l3WjJWLVMVepTucJ+2AJksa6DrprFDD7SPGWpUaN8eu1skavFVAm2hlQSr+ZmQCUAPcAiwslOmzZGzWm87FsTyoPUrE7yTaAnF450EYlRtyb7cgjKLCyCmLrNebkFVe2AIv2A1CkiFA92ZT4y76hYOw6innMvr9jF+Ko0KU7FGv/EQlSd3NIqGkAJExGAGGR2fGPTaLknO24z0HvLX2jvB9l/vle7vLacfwZVXG7chK26KAhV5ledI4Ay0gz28AbBZx3vXpj/nZKLTn7Bk8ARKaMnrW0KpK9E9JiUlxYIRQhvCwNj/lBvwaDl0XxAvgcwsi5rf4dfT9qC/UB2+9iHoZ3VpiiJz9SGbsKjLaJQMpKRgOk16WEwQ1F0kgwY8To5Fc09755oVWBwuEK/9yQmDLkXRb+6/Wsbhi0ay7sUkMRMUILeGb5WDCa/7gLBOvV+vOZQyP9WFgLrFSeTpg6LuUMO7hHXo+Z9irtmNDGhJllXSj+Blp0jQpWDgEb2mmak5lxYjXZns6vkYi+9+88CDK3W7MDaC+B/e0OWf0GIR5RBJUovoSuyoI9MaV3X3D+mOUkFDUjyUhvr3b6fjf15hcYa1hOIVvwdH1DFiu6GLL/Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
