travis:
  secure:
    BINSTAR_TOKEN: b1h8pXUxt/BFJSNyYH3lmALTQpbuKuVKIlFombiFdEkj0zhx+YxHop80w8GestR7Q3bNggCv90N4mXyf7p/W+n1gQEPpSr8hcdFa95+Jy+nbpY3EnFyVrIO7ChazyuRSOzU/iqR9HVOCfZj7Gb5Py2KVZK1QT0rrth72ASseWun+xQFtuLQMqkFFJIDMONaWw1CloK3MMRSqcNAaLqsHGnU7jGWWbDdTvf5dG392MiFAh6UVymG5Vjc5QHfXA8zuHClEj72OoC+ag5K8BOdiGICsQ5g2hYPQV4xVN/OTo/XFnz11sJR/cAjWzJjVoEoqBjN6tQ2Rhn//OLyB/alSE3V0Ca4l3UayposIMH0bxmin74jFyaxmk9aLnYWchokSUuwESnmtLKZXZ/LbHvSeQ6Y6VqEmyEdJpVzVCJvrX21oOVYn36H/qk6gAEOTKB4xcYv5yAx2qTOwoEYzgTFNXFKb0ENIRtQDPnWr4A7sS2gTExD6ze2ldoryrgjjzUK3aEUVDmwux+N2zEOyseteE7vrTwliliFSUnLeaf6UUAoIl6xyHquy0LpaJS/z6vATeQ9dzt8QRdGLUjgoSU2v+xIYVllqmFAtGMOUmsLXfAPH9UBArBjLHQxvQvQzAThtG8AG4Y4K9Fa6HHpNYbJMQwK6rOXgULq+sPhGmh7KssQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
