travis:
  secure:
    BINSTAR_TOKEN: K5cIJFpm3wy+QRvrS6TbpDMcMaVifCCFASr+ikG81JAUusFdASto/+vlDi98D3ZhROEU30LGBgn6CvHtqrUuwScLQ2bLFd3RRPQj6J4B7405lPorWGoLQ+F1yDfnUXteIK1Lb1KXSmMNtOYJEP3SWLQH1zmPHt+OuQ15F6cg9BnMhZP7et7wSyWxwcPrfq++CB0a6qKHRciHseh/FYhdIW2a+/NIRylkoWu2YMJffvs3wjlhQ6eL+d87OL5jW/OUrOzeuj4swV+Hhw5Opk+/+/WY42rXzyjLVAXndeloCddxV6o0OnZ3rAfD+H//WnbzxLJBn7zD4c06GOWjJFLVwfgctBGla63xNqxkG7t3VIYAS3x70sPEMVKIhWjahan0rHLoNTteaB1CxLXxIIbgSGVwjrVpVB1LFHwVyNpiR3mGZqVdST5wuBJD8eoBbEjgurAHD34gl5TUryudFxiodApvNmNMZ0r+iiR1fX9GNqfiPuUQyh+hVvrBzTHr1q0dEMudJNbg+D3KKcWpsJ0UYPzdtrixTbJkcINa36lljdtNPwAnlnM5tZmmg7KWV+zZp1xkohOiimmmI0og0qpyIenRpJnJoLACW4N4mZ52WFBq9dKw7qtbQOYjx4l3Gc5We3Jgyhq5wDkVsGgsSOPgmmd3a0Z6SIrM45EkW3ZPagE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
